### PR TITLE
fix trivial but serious bug in configure.ac

### PR DESCRIPTION
**Pull request by jeffhammond**
CPPFLAGS is for C preprocessing, not C++ compilation.  setting
-std=c++11 here causes this flag to be used with the C compiler.

more importantly, it causes CPP=/lib/cpp to be inferred, at least on
Mac, and this does not work at all.

### CODE REVIEW

**Comment by shiozaki** [comment]
I am not sure why this is there. The previous line must be setting CXXFLAGS (see m4/ax_cxx_compile_stdcxx_11.m4), so best to remove this line instead.

**Comment by jeffhammond** [comment]
I haven't tested it, but that sounds better, since it will allow the C++11 macro to set the appropriate C++11 flag, not just the one that works for GCC, Clang and Intel.

**Comment by jeffhammond** [comment]
I implemented your suggested fix and merged with master.

**Comment by shiozaki** [comment]
Thanks much!

**Pull request merged**
